run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - govet
    - gofumpt
    - deadcode
    - errcheck
    - gosimple

linters-settings:
  govet:
    disable:
      - stdmethods

  gofumpt:
    extra-rules: true
    module-path: github.com/dominikbraun/graph